apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
        - name: jellyfin
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8096
          volumeMounts:
            - name: config-volume
              mountPath: {{ .Values.persistence.config.mountPath }}
            - name: media-volume
              mountPath: {{ .Values.persistence.media.mountPath }}
      volumes:
        - name: config-volume
          persistentVolumeClaim:
            claimName: jellyfin-config-pvc
        - name: media-volume
          persistentVolumeClaim:
            claimName: jellyfin-media-pvc
