{{- if .Values.persistence.config.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-config-pv
spec:
  capacity:
    storage: {{ .Values.persistence.config.size }}
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.persistence.config.accessMode }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.persistence.config.storageClass }}
  hostPath:
    path: /srv/jellyfin/config
{{- end }}
