apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  ports:
    - port: 8096
      targetPort: 8096
      nodePort: 30080
  selector:
    app: jellyfin
